[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "basic_threads"

[[bin]]
name = "message_transfer"

[[bin]]
name = "mutex"

[dependencies]
